### ISSUE TITLE
can't get the exported data

### ISSUE THREAD

**Issue by remyahalza** [microsoft/iomt-fhir#103]
I created fhir server using following link
https://github.com/microsoft/fhir-server/blob/main/docs/DefaultDeployment.md

then i got fhir server as app service, data stored in cosmosdb
Then i created iomt fhir using your repo, and put the fhir server url as the above app service link,

After creating all , i just create iot central application in azure with continous patient monitoring template,

Then create export on iot central application, but i cant get the eported data through postman

**Comment by dustinburson** [comment]
If you are using the device templates found in https://github.com/microsoft/iomt-fhir/tree/master/sample/templates/sandbox please make sure you are using the legacy export option.  IoT Central has changed the schema in their new export .  We are planning on adding updated templates as examples but they aren't available currently.  If you want to use the new IoT Central export it is supported but you will need to create the templates.  The template type you want to use is documented here https://github.com/microsoft/iomt-fhir/blob/master/docs/Configuration.md#iotcentraljsonpathcontenttemplate

Another consideration and key piece of information is how your authenticating the connector to the FHIR service.  Did you use the managed identity template to deploy the connector?  If so did you add the managed identity of the connector as a FHIR Data Contributor on FHIR service?

**Comment by dustinburson** [comment]
@remyahalza we recently updated the Sandbox documentation and scripts to used the latest export, please see #109.
