### ISSUE TITLE
IoMT-FHIR Connector has no error even when it fails to ingest data to FHIR

### ISSUE THREAD

**Issue by liupeirong** [microsoft/iomt-fhir#105]
When running in `Create` mode with a `device ID` and no `patient ID` mapped, `MeasurementCollectionToFhir` runs successfully without any error, but the data isn't ingested to Azure FHIR. 

Similarly, if there is an existing `device ID` mapped to a `patient ID` in FHIR, and you ingest data with the same `device ID` but different `patient ID`, everything appears to succeed, but the data isn't ingested to FHIR. 

In both cases, the `MeasurementCollectionToFhir` function should indicate an error because it failed to ingest the data to FHIR.

**Comment by dustinburson** [comment]
@liupeirong these are non-recoverable errors.  The data as configured is bad/invalid.  Failing the import will halt all progress in the pipeline.  This errors are recorded as telemetry here https://github.com/microsoft/iomt-fhir/blob/master/docs/Debugging.md#telemetry-collected.  You can monitor the telemetry for such data issues.  If you aren't seeing the telemetry for these errors then please reopen the details.
