### ISSUE TITLE
Feature request: MeasurementCollectionToFHIR function to support "POST" data to multiple FHIR servers.

### ISSUE THREAD

**Issue by venkateshdevireddy5353** [microsoft/iomt-fhir#130]
@Team I would like to add a new feature to support the Transformed data to be posted to multiple FHIR servers or at least synchronization service between parent and child FHIR servers, where in the current setup. it supports the data to be posted to only one FHIR server that has been configured while deploying the connector.

pointers for the same is much appreciated.

**Comment by dustinburson** [comment]
Hello @venkateshdevireddy5353 this can be achieved with the existing architecture. In OSS you can have one device event hub but add additional consumer groups.  For each consumer group you would have a SA Job + Azure Function that targets the specific FHIR services you wish to export the data to.

In our new preview version we released to PaaS (https://docs.microsoft.com/en-us/azure/healthcare-apis/iot/) we have decoupled the normalization from the destination.  While preview is currently limited to just one FHIR Destination at this time we  could support more if there is enough demand for the feature.  Would you be able to describe your specific scenario better for us to understand?

**Comment by venkateshdevireddy5353** [comment]
Hi @dustinburson Thanks for your prompt response, I will just explain the scenario that I am trying to make in our development, We have two FHIR servers deployed(1. Azure API for FHIR and 2. Microsoft open source FHIR server) and we have an IoMT connector deployed with which we are using the services of "Azure API for FHIR" and the process is smooth but we also want to send the data to second server which is MS FHIR Server(which doesn't have any restrictions, I mean to say to make a POST request to it, there are no restrictions), using the connector that we have deployed to Azure App service, how can we send the data to our other server(MS open FHIR server).

if you could give us some pointers on how to achieve this that would be very much helpful.

**Comment by venkateshdevireddy5353** [comment]
Hi @dustinburson I was trying the above approach but couldn't find the OS FHIR Server's resource ID and it's not allowing me to add a URL as well and btw our OS FHIR server is deployed via AKS.

**Comment by venkateshdevireddy5353** [comment]
Nope, I have deployed the Microsoft's IoMT-FHIR connector in Azure portal and trying to send the data to a Open Source Microsoft FHIR Server deployed in AKS.(Note: MS IoMT-FHIR connector is working fine with Azure API for FHIR by MS, but wanted to add this additional functionality as well), please help me with some pointers.

**Comment by dustinburson** [comment]
Supported in PaaS, Azure Function solution in OSS has been deprecated in favor of containerized services.
