### ISSUE TITLE
DataMapper tool not evaluating JmesPath expressions / MatchedTokens

### ISSUE THREAD

**Issue by HariKorrapati** [microsoft/iomt-fhir#139]
Based on the documentation available at [Calculatedcontenttemplate](https://github.com/microsoft/iomt-fhir/blob/master/docs/Configuration.md#calculatedcontenttemplate), we can choose to use JmesPath expression language instead JSON Path language. However we see this is not working with the data mapper tool.

We feel there are multiple issues around the data mapper tool
1. JmesPath expressions are not working, also tried the custom function fromUnixTimestampMs mentioned in [fromUnixTimestampMs](https://github.com/microsoft/iomt-fhir/blob/master/docs/CustomFunctions.md#fromunixtimestampms)
2. [Matched Token](https://github.com/microsoft/iomt-fhir/blob/master/docs/Configuration.md#matched-token) example provided in the documentation is not working. 
<img width="955" alt="MatchedToken-Error" src="https://user-images.githubusercontent.com/32130561/138866286-d776d26d-829b-42a4-8bfb-8573ae56403a.png">
3. If the expressions have AND operator (**&&**), it is being escaped to **&amp;amp;&amp;amp;** everytime the template is saved and reloaded. However the tool fails to evaluate the expressions if the && operator is escaped
<img width="952" alt="Ampersand_EscapeSequence" src="https://user-images.githubusercontent.com/32130561/138866676-024e8a61-d0c6-4a70-8fc2-9e0b146f2c17.png">

4. Data mapper tool is always treating the template type as JSON Path, even if we use Jmes expressions.

**Comment by HariKorrapati** [comment]
Thanks @dustinburson for the response. 

While the tool may not support the CalculatedContent yet, I noticed that there are test cases around CalculatedContent template and they do work fine. However when we use the templates given in test cases on server, we are getting the below error
`Exception while executing function: NormalizeDeviceData One or more errors occurred. (Unable to extract required value for [DeviceIdExpression] using $.Body.deviceId)`

Is there anything we are missing? 

References:
Test Class: CalculatedFunctionContentTemplateDocumentationTests
Test Case: MultipleMatches_And_UsingParentScope_Test

**Comment by dustinburson** [comment]
DataMapper tool has been retired in favor of the mapping debugger that is built into the PaaS service in Azure portal.
