### ISSUE TITLE
Can we get sandbox deployment instructions for OSX as well?

### ISSUE THREAD

**Issue by bookofdom** [microsoft/iomt-fhir#31]
https://github.com/microsoft/iomt-fhir/blob/master/docs/Sandbox.md works for Windows users how about Mac and Linux?

**Comment by SharonHart** [comment]
@bookofdom I believe that the instructions assumes that you are running for within a powershell console, which is available for installation in [Mac and Linux](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell?view=powershell-7.1) as well.
