### ISSUE TITLE
Aggregation randomly generates split observations for SampledData mapping

### ISSUE THREAD

**Issue by mmacagno** [microsoft/iomt-fhir#74]
I have observed a few cases of split observations.

I have mappings that aggregate data on a minute by minute basis:

![image](https://user-images.githubusercontent.com/2315384/95770997-26fdc300-0c6f-11eb-8427-01c83d2fe777.png)

Instead of having a single observation with the aggregated data for the hour, I sometime observe split observations:

Observation 1:
![image](https://user-images.githubusercontent.com/2315384/95771182-78a64d80-0c6f-11eb-8151-4e073479d9eb.png)

Observation 2:
![image](https://user-images.githubusercontent.com/2315384/95771128-60cec980-0c6f-11eb-8106-a3b03e24be83.png)

As you can observe, the sampledData is accumulated up to a point on the first observation, and continues on the second.

**Comment by dustinburson** [comment]
Thank you for submitting the issue.  Can you also share the FHIR mapping template used to generate the observations?

**Comment by mmacagno** [comment]
Thanks @dustinburson - sending you the template privately.

**Comment by mmacagno** [comment]
Upon private discussion and investigation, this seems to be a bug in the source of the IOT Hub events.
Closing this. External issue.

thanks @dustinburson
