### ISSUE TITLE
[Question] What's the purpose of Stream Analytics?

### ISSUE THREAD

**Issue by giacomodeliberali** [microsoft/iomt-fhir#77]
We have successfully deployed the connector, but I still haven't figured out the Stream Analytics role. I saw #68, and I was wondering the implications of directly invoking the FHIR conversion function from the normalized data Event Hub, as #68 [seems to be doing](https://github.com/microsoft/iomt-fhir/blob/personal/duburson/remove-sa-prototype/src/func/Microsoft.Health.Fhir.Ingest.Host/IomtConnectorFunctions.cs#L31).

Do you have any plan to merge that pull request? Can we safely get rid of the SA? Does it have anything to do with [Output Error Policies](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-output-error-policy#:~:text=When%20an%20error%20occurs%2C%20Azure,default%20output%20error%20handling%20policy.) for failed jobs? Or is it only meant to efficently support [SampledData measurement type](https://www.hl7.org/fhir/datatypes.html#SampledData)? 

Sorry for all those questions but I'm trying to clarify my ideas 😅

**Comment by dustinburson** [comment]
Hello @giacomodeliberali, 

Stream Analytics is used to group and buffer data prior to converting to FHIR.  The main reason is for efficiently supporting the SampledData type and the different grouping strategies like hourly observations of data or correlation id assosication.  

If you don't plan on using SampledData to render time series data you could technically remove SA though you would need to replace the HttpTrigger Azure function with an EventHubTrigger from the Normalized Event Hub directly.  One down side to removing SA, even if you don't need to generate SampledData is if you have a device that sends duplicate data it will result in multiple updates on the FHIR server

The PR your referenced, #68, we don't plan on completing as is.  This was a prototype work stream the team was investigating. The team is working on a more full featured version that is currently in PR #78.  You are welcome to use once complete.
