### ISSUE TITLE
Configuration.md documentation update needed

### ISSUE THREAD

**Issue by softcraftsman** [microsoft/iomt-fhir#93]
Configuration.md documentation is out of date. The links to the source files have changed.

Also, it's not clear what the template is transforming it into.  An example of the filled out values on IMeasurement would be helpful.

Thirdly, a method to test and verify transforms based on sample data would be most helpful.

**Comment by dustinburson** [comment]
@softcraftsman thank you for the feedback

On the last item there are two options.

At the beginning of the year we released the following tool https://github.com/microsoft/iomt-fhir#iomt-connector-data-mapper to help with mapping.  You can use this to test based on sample payloads.

The other option is adding examples to the existing unit tests for your specific needs.
